---
name: Commit
on: push

jobs:
  tests:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setting up tox environment
        uses: docker://kiwicom/tox:3.25.0
        env:
          TOXENV: ${{ matrix.toxenv }}
          XDG_CACHE_HOME: /tmp/cache
        with:
          args: >
            sh -c
            "
            mkdir -p reports ;
            tox -e tests-$TOXENV -- --junitxml=reports/$TOXENV/test_report.xml --cov structlog_sentry --cov-report xml --cov-config .coveragerc --cov-append --cov-report xml:reports/coverage.xml
            "
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
    strategy:
      matrix:
        toxenv: [py39, py310, py311]

  lint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setting up tox environment
        uses: docker://kiwicom/tox
        env:
          XDG_CACHE_HOME: /tmp/cache
        with:
          args: >
            sh -c
            "
            mkdir -p reports ;
            tox -e pylint
            "
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}

  commitsar:
    name: Commit message style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run commitsar
        uses: docker://aevea/commitsar

  pre-commit:
    name: Static checks
    runs-on: ubuntu-latest
    container: kiwicom/pre-commit:3.6.0


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache
        uses: actions/cache@v4
        with:
          path: .pre-commit-cache
          key: static-checks-${{ hashFiles('.pre-commit-config.yaml') }}

      # git checkout is not creating a working git folder, it has dubious ownership if not configured
      # The pre-commit hook will not work on this original git folder
      # https://github.com/pre-commit/pre-commit/issues/2125
      - name: fix git
        run: git config --system --add safe.directory '*'

      - run: mkdir -p .pre-commit-cache
      - run: pre-commit install --install-hooks
      - run: pre-commit run -a
        env:
          SKIP: no-commit-to-branch
