---
name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    name: Publish PyPI package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install dependencies
        run: >-
          python -m
          pip install
          setuptools
          wheel
          --user
      - name: Build wheels
        run: >-
          python
          setup.py
          sdist
          bdist_wheel
      - name: Publish package to pypi.org
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
